#  MIT License
#
#  Copyright (c) 2021 Vilius Sutkus <ViliusSutkus89@gmail.com>
#
#  https://github.com/ViliusSutkus89/Sample_Android_Library-MavenCentral-Instrumented_Tests
#  .github/workflows/privilegedBuild.yml - v1.1.7
#
#  Permission is hereby granted, free of charge, to any person obtaining a copy
#  of this software and associated documentation files (the "Software"), to deal
#  in the Software without restriction, including without limitation the rights
#  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#  copies of the Software, and to permit persons to whom the Software is
#  furnished to do so, subject to the following conditions:
#
#  The above copyright notice and this permission notice shall be included in all
#  copies or substantial portions of the Software.
#
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#  SOFTWARE.

name: privilegedBuild
on:
  workflow_dispatch:
  push:
    branches: master
    paths-ignore:
      - '**.md'
      - '.github/workflows/manualVersionIncrement*.yml'
      - '.github/workflows/unprivilegedBuild.yml'

env:
  ANDROID_NDK:        "22.1.7171670"
  ANDROID_CMAKE:      "3.10.2.4988404"
  TARBALL_CACHE_KEY:  "tarballs-key-3"

permissions:
  actions: none
  checks: none
  contents: none
  deployments: none
  issues: none
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  buildDependencies:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        abi: [ x86, x86_64, armeabi-v7a, arm64-v8a ]
        buildType: [ Debug, Release ]
        include:
          - buildType: Debug
            CMakeBuildType: Debug
          - buildType: Release
            CMakeBuildType: MinSizeRel
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 8
      - uses: android-actions/setup-android@v2
      - run: sdkmanager "ndk;${{env.ANDROID_NDK}}" "cmake;${{env.ANDROID_CMAKE}}"
      # gperf is required by fontconfig, gettext is required by libfontforge
      - run: sudo apt-get install --yes gperf gettext
      # apt-get offers meson-0.53.2, pdf2htmlEX-Android requires meson-0.54.2 or newer
      - run: pip3 install --user meson

      - name: Cache tarballs
        uses: actions/cache@v2
        with:
          key: ${{ env.TARBALL_CACHE_KEY }}
          path: dependency-builder/src/main/cpp/tarballs

      - run: ./dodownloadtarballs --serial

      - name: Build dependencies of pdf2htmlEX-Android
        run: ./gradlew dependency-builder:assemble${{ matrix.buildType }} -Pabi=${{ matrix.abi }}

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: dependencyBuildLogs-${{ matrix.buildType }}-${{ matrix.abi }}
          path: |
            dependency-builder/.cxx/cmake/**/*-configure-*.log
            dependency-builder/.cxx/cmake/**/*-build-*.log

      - name: Gather licenses
        if: matrix.abi == 'armeabi-v7a' && matrix.buildType == 'Release'
        run: ./gradlew gatherLicenses -Pabi=${{ matrix.abi }}

      - name: Artifact gathered licenses
        if: matrix.abi == 'armeabi-v7a' && matrix.buildType == 'Release'
        uses: actions/upload-artifact@v2
        with:
          name: licenses
          path: dependency-builder/build/licenses.xml

      - name: Prepare built dependencies for artifacting
        run: |
          mkdir -p i/${{ matrix.abi }}/{bin,include,lib,share}
          mv dependency-builder/build/installed/${{ matrix.CMakeBuildType }}/${{ matrix.abi }}/bin/pkg-config i/${{ matrix.abi }}/bin/
          mv dependency-builder/build/installed/${{ matrix.CMakeBuildType }}/${{ matrix.abi }}/bin/pkg-config-dynamic i/${{ matrix.abi }}/bin/
          mv dependency-builder/build/installed/${{ matrix.CMakeBuildType }}/${{ matrix.abi }}/include/pdf2htmlEX.h i/${{ matrix.abi }}/include/
          mv dependency-builder/build/installed/${{ matrix.CMakeBuildType }}/${{ matrix.abi }}/lib/pkgconfig i/${{ matrix.abi }}/lib/
          mv dependency-builder/build/installed/${{ matrix.CMakeBuildType }}/${{ matrix.abi }}/lib/libpdf2htmlEX.so i/${{ matrix.abi }}/lib/
          mv dependency-builder/build/installed/${{ matrix.CMakeBuildType }}/${{ matrix.abi }}/share/pkgconfig i/${{ matrix.abi }}/share/

      - name: Artifact built dependencies
        uses: actions/upload-artifact@v2
        with:
          name: installed-dependencies-${{ matrix.buildType }}-${{ matrix.abi }}
          path: i

      - name: Artifact assets
        uses: actions/upload-artifact@v2
        with:
          name: results-for-downstream-aar-${{ matrix.buildType }}-${{ matrix.abi }}
          path: dependency-builder/build/includeTheseInDownstreamAAR

  buildLibrary:
    needs: buildDependencies
    runs-on: ubuntu-20.04
    environment: LibraryKeyAndSonatypeAccess
    outputs:
      STAGING_REPO_URL: ${{ steps.sonatype.outputs.stagingRepoUrl }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 8
      - uses: android-actions/setup-android@v2
      - run: sdkmanager "ndk;${{env.ANDROID_NDK}}" "cmake;${{env.ANDROID_CMAKE}}"

      - name: Cache tarballs
        uses: actions/cache@v2
        with:
          key: ${{ env.TARBALL_CACHE_KEY }}
          path: dependency-builder/src/main/cpp/tarballs

      - run: ./dodownloadtarballs --serial

      - name: Download all artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: Print out downloaded artifacts for debugging purposes
        run: find artifacts

      - name: Prepare downloaded artifacts
        run: |
          mkdir -p dependency-builder/build
          mv artifacts/licenses/licenses.xml dependency-builder/build

          mkdir -p dependency-builder/build/installed/{Debug,MinSizeRel}
          mv artifacts/installed-dependencies-Debug-x86/x86                   dependency-builder/build/installed/Debug/
          mv artifacts/installed-dependencies-Debug-x86_64/x86_64             dependency-builder/build/installed/Debug/
          mv artifacts/installed-dependencies-Debug-armeabi-v7a/armeabi-v7a   dependency-builder/build/installed/Debug/
          mv artifacts/installed-dependencies-Debug-arm64-v8a/arm64-v8a       dependency-builder/build/installed/Debug/
          mv artifacts/installed-dependencies-Release-x86/x86                 dependency-builder/build/installed/MinSizeRel/
          mv artifacts/installed-dependencies-Release-x86_64/x86_64           dependency-builder/build/installed/MinSizeRel/
          mv artifacts/installed-dependencies-Release-armeabi-v7a/armeabi-v7a dependency-builder/build/installed/MinSizeRel/
          mv artifacts/installed-dependencies-Release-arm64-v8a/arm64-v8a     dependency-builder/build/installed/MinSizeRel/

          mkdir -p dependency-builder/build/includeTheseInDownstreamAAR/{debug,release}/{assets,jniLibs}
          mv artifacts/results-for-downstream-aar-Debug-x86/debug/assets/x86                      dependency-builder/build/includeTheseInDownstreamAAR/debug/assets/
          mv artifacts/results-for-downstream-aar-Debug-x86_64/debug/assets/x86_64                dependency-builder/build/includeTheseInDownstreamAAR/debug/assets/
          mv artifacts/results-for-downstream-aar-Debug-armeabi-v7a/debug/assets/armeabi-v7a      dependency-builder/build/includeTheseInDownstreamAAR/debug/assets/
          mv artifacts/results-for-downstream-aar-Debug-arm64-v8a/debug/assets/arm64-v8a          dependency-builder/build/includeTheseInDownstreamAAR/debug/assets/
          mv artifacts/results-for-downstream-aar-Debug-x86/debug/jniLibs/x86                     dependency-builder/build/includeTheseInDownstreamAAR/debug/jniLibs/
          mv artifacts/results-for-downstream-aar-Debug-x86_64/debug/jniLibs/x86_64               dependency-builder/build/includeTheseInDownstreamAAR/debug/jniLibs/
          mv artifacts/results-for-downstream-aar-Debug-armeabi-v7a/debug/jniLibs/armeabi-v7a     dependency-builder/build/includeTheseInDownstreamAAR/debug/jniLibs/
          mv artifacts/results-for-downstream-aar-Debug-arm64-v8a/debug/jniLibs/arm64-v8a         dependency-builder/build/includeTheseInDownstreamAAR/debug/jniLibs/
          mv artifacts/results-for-downstream-aar-Release-x86/release/assets/x86                  dependency-builder/build/includeTheseInDownstreamAAR/release/assets/
          mv artifacts/results-for-downstream-aar-Release-x86_64/release/assets/x86_64            dependency-builder/build/includeTheseInDownstreamAAR/release/assets/
          mv artifacts/results-for-downstream-aar-Release-armeabi-v7a/release/assets/armeabi-v7a  dependency-builder/build/includeTheseInDownstreamAAR/release/assets/
          mv artifacts/results-for-downstream-aar-Release-arm64-v8a/release/assets/arm64-v8a      dependency-builder/build/includeTheseInDownstreamAAR/release/assets/
          mv artifacts/results-for-downstream-aar-Release-x86/release/jniLibs/x86                 dependency-builder/build/includeTheseInDownstreamAAR/release/jniLibs/
          mv artifacts/results-for-downstream-aar-Release-x86_64/release/jniLibs/x86_64           dependency-builder/build/includeTheseInDownstreamAAR/release/jniLibs/
          mv artifacts/results-for-downstream-aar-Release-armeabi-v7a/release/jniLibs/armeabi-v7a dependency-builder/build/includeTheseInDownstreamAAR/release/jniLibs/
          mv artifacts/results-for-downstream-aar-Release-arm64-v8a/release/jniLibs/arm64-v8a     dependency-builder/build/includeTheseInDownstreamAAR/release/jniLibs/

          find dependency-builder/build/installed -type f -name 'pkg-config' -exec chmod +x {} \;
          find dependency-builder/build/installed -type f -name 'pkg-config-dynamic' -exec chmod +x {} \;

      - run: ./gradlew build

      - run: mv pdf2htmlEX/build/reports/lint-results.html library-lint-report.html
      - uses: actions/upload-artifact@v2
        with:
          name: library-lint-report.html
          path: library-lint-report.html

      - name: 'Publish to Sonatype'
        run: ./gradlew publishToSonatype closeSonatypeStagingRepository | tee publishToSonatype.log
        # bash has pipefail on by default, which is needed for tee to fail, if gradle fails
        shell: bash
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASS: ${{ secrets.SIGNING_PASS }}

      - name: 'Parse Sonatype repository'
        id: sonatype
        # publishToSonatype.log contains a line looking like this:
        # Created staging repository 'comviliussutkus89-1055' at https://oss.sonatype.org/service/local/repositories/comviliussutkus89-1055/content/
        run: perl -ne 'print "::set-output name=stagingRepoUrl::$2\n::warning ::$1\n" if /^(Created staging repository .+ at (.+))$/' < publishToSonatype.log

      - run: ./gradlew publishToMavenLocal
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASS: ${{ secrets.SIGNING_PASS }}

      - run: tar -cvf maven-local.tar ~/.m2
      - uses: actions/upload-artifact@v2
        with:
          name: maven-local
          path: maven-local.tar

  buildSampleAppStaging:
    needs: buildLibrary
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 8
      - uses: android-actions/setup-android@v2

      - name: Prepare sample app for staging repository
        run: ./ci-scripts/prepareSampleAppForStagingRepository android-sample-app app --output=build/sampleapp-staging --repository=${{ needs.buildLibrary.outputs.STAGING_REPO_URL }}

      - name: Build sample app from staging library
        run: ./gradlew build
        working-directory: build/sampleapp-staging

      - uses: actions/upload-artifact@v2
        with:
          name: sampleapp-staging-apks
          path: build/sampleapp-staging/app/build/outputs/apk/**/*.apk

      - run: mv build/sampleapp-staging/app/build/reports/lint-results.html sampleapp-staging-lint-report.html
      - uses: actions/upload-artifact@v2
        with:
          name: sampleapp-staging-lint-report.html
          path: sampleapp-staging-lint-report.html

  runInstrumentedTests:
    needs: buildLibrary
    # Only macos VMs are available with exposed CPU extensions to run hardware accelerated emulator
    runs-on: macos-10.15
    strategy:
      fail-fast: false
      matrix:
        include:
          # Oldest API supported by NDK
          - arch: x86
            api-level: 16
            api-type-target: default
          # Oldest x86_64 image
          - arch: x86_64
            api-level: 21
            api-type-target: default
          # Latest x86 image
          - arch: x86
            api-level: 30
            api-type-target: google_apis
          # Latest image
          - arch: x86_64
            api-level: 31
            api-type-target: google_apis
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 8
      - uses: android-actions/setup-android@v2

      - run: ./ci-scripts/prepareLibraryTestsForStagingRepository pdf2htmlEX --output=build/lib-staging --repository=${{ needs.buildLibrary.outputs.STAGING_REPO_URL }}

      - uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: ${{ matrix.arch }}
          target: ${{ matrix.api-type-target }}
          script: ./gradlew connectedCheck
          working-directory: build/lib-staging

      - run: tar -cvf instrumentedTestsReport-${{ matrix.api-level }}-${{ matrix.arch }}.tar build/lib-staging/pdf2htmlEX/build/reports/androidTests/connected
        if: always()
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: instrumentedTestsReport-${{ matrix.api-level }}-${{ matrix.arch }}.tar
          path: instrumentedTestsReport-${{ matrix.api-level }}-${{ matrix.arch }}.tar

  releaseSonatype:
    environment: SonatypeAccess
    # Needs to depend on buildLibrary too, to obtain STAGING_REPO_URL
    needs: [runInstrumentedTests, buildLibrary]
    runs-on: ubuntu-20.04
    outputs:
      ARTIFACTS: ${{ steps.promote.outputs.artifacts }}
    steps:
      - uses: ViliusSutkus89/promote-Nexus-repository-to-MavenCentral@v1
        id: promote
        with:
          repositoryURL: ${{ needs.buildLibrary.outputs.STAGING_REPO_URL }}
          sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
          sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}

  releaseGitHub:
    environment: TenMinuteWait
    needs: releaseSonatype
    permissions:
      # Permission needed to create GitHub release and version increment commit.
      contents: write
    outputs:
      RELEASE_TAG: "v${{ steps.updateDownstreamVersion.outputs.version }}"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          # A branch is required for post release version increment commit
          ref: ${{ github.event.ref }}

      - uses: ViliusSutkus89/WaitForURLsToBeAvailable@v1
        with:
          URLs: ${{ needs.releaseSonatype.outputs.ARTIFACTS }}
          # First attempt to promote pdf2htmlEX-Android didn't go through in 30 minutes
          # Raise the timeout to TenMinuteWait + tryCount
          tryCount: 60

      - run: ./ci-scripts/updateDownstreamVersion
        id: updateDownstreamVersion

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update README.md and sample app to match versions with to be released library version (${{ steps.updateDownstreamVersion.outputs.version }})"
          file_pattern: ${{ steps.updateDownstreamVersion.outputs.files }}

      - uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "v${{ steps.updateDownstreamVersion.outputs.version }}"
          name: "${{ github.event.repository.name }} v${{ steps.updateDownstreamVersion.outputs.version }}"
          artifacts: "artifacts/maven-local.tar/maven-local.tar,artifacts/library-lint-report.html/library-lint-report.html,artifacts/instrumentedTestsReport-*-*.tar/instrumentedTestsReport-*-*.tar"
          bodyFile: "UpcomingReleaseNotes.md"

      - run: ./ci-scripts/incrementVersion --patch
        id: postReleaseVersionIncrement

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Post release library version increment to ${{ steps.postReleaseVersionIncrement.outputs.newVersion }} (from ${{ steps.postReleaseVersionIncrement.outputs.oldVersion }})"
          file_pattern: ${{ steps.postReleaseVersionIncrement.outputs.files }}

      - run: echo -n > UpcomingReleaseNotes.md
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Post release truncation of UpcomingReleaseNotes.md"
          file_pattern: UpcomingReleaseNotes.md

  buildSampleApp:
    environment: SampleAppKeystore
    needs: releaseGitHub
    permissions:
      # Permission needed to attach artifact to GitHub release.
      contents: write
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: refs/tags/${{ needs.releaseGitHub.outputs.RELEASE_TAG }}
      - uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 8
      - uses: android-actions/setup-android@v2

      - id: decodeSampleAppKeystore
        run: |
          echo "${{ env.APP_SIGNING_KEYFILE_BASE64 }}" | base64 --decode - > "$HOME/com.viliussutkus89.android.pdf2htmlex.sampleapp.jks"
          echo "::set-output name=APP_SIGNING_KEYFILE::$HOME/com.viliussutkus89.android.pdf2htmlex.sampleapp.jks"
        env:
          APP_SIGNING_KEYFILE_BASE64: ${{ secrets.APP_SIGNING_KEYFILE_BASE64 }}

      - run: ./gradlew build
        working-directory: android-sample-app
        env:
          APP_SIGNING_KEYFILE: ${{ steps.decodeSampleAppKeystore.outputs.APP_SIGNING_KEYFILE }}
          APP_SIGNING_PASS: ${{ secrets.APP_SIGNING_PASS }}
          APP_SIGNING_ALIAS: ${{ secrets.APP_SIGNING_ALIAS }}

      - run: mv android-sample-app/app/build/reports/lint-results.html sampleapp-lint-report.html

      - name: Attach sample application to GitHub Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ needs.releaseGitHub.outputs.RELEASE_TAG }}
          name: "${{ github.event.repository.name }} v${{ steps.updateDownstreamVersion.outputs.version }}"
          allowUpdates: true
          artifacts: "android-sample-app/app/build/outputs/apk/**/*.apk,sampleapp-lint-report.html"
